### ISSUE TITLE
Add a copy link option?

### ISSUE THREAD

**Issue by karuppiah7890** [sriv/gchat-threadlink#1]
I think many would like to copy the link to the thread as I feel that's the main use case here. Currently we have to right click and copy link. Providing an option to copy the link would be awesome. Probably like some small copy icon. 

Or we can change the current # to act as a copy instead of a link?

Thoughts?

**Comment by sriv** [comment]
Hmm - I thought "rightclick -> copy link location" would do the trick...

**Comment by karuppiah7890** [comment]
? So, close issue? Okay

**Comment by sriv** [comment]
wasn't hinting at closing it. always open to improving things.

Would you like to take a stab at a PR?

**Comment by sriv** [comment]
I now realize the convenience of having such a feature :) 

It takes 3 clicks to get the URL and we could bring it down to one. So +1 for this.

**Comment by karuppiah7890** [comment]
Let me take a look
